### ISSUE TITLE
current build is failing?

### ISSUE THREAD

**Issue by pattishih** [austintackaberry/jobsort#1]
Hey Austin! Thanks for sharing this. I'm just playing around, as I'm very new to backend development. What's wrong with the current build and what should I be looking into to fix it? Thanks!

**Comment by austintackaberry** [comment]
Hey! Sorry, I just saw this...not used to getting issues. What do you mean when you say "What's wrong with the current build"? When I go to jobsort.tech, it seems like it is working fine.
